name: 🩺 Continuous integration
description: Build and test
on: workflow_call
defaults:
  run:
    shell: pwsh
permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
jobs:
  test:
    name: 🧪 Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: 📥 Check out script source
        uses: actions/checkout@v6
      - name: 🏗️ Setup .NET
        if: hashFiles('/*.slnx')
        uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: '10.0.x'
      - name: 🏭 Build module .dll
        if: hashFiles('/*.slnx')
        run: dotnet publish
      - name: 🏭 Build module .psm1
        if: hashFiles('/scripts/Build-ThisModule.ps1')
        run: ./scripts/Build-ThisModule.ps1
      - name: 🔬 Analyze module style
        uses: microsoft/psscriptanalyzer-action@v1.0
        if: hashFiles('/src/public/*.ps1')
        with:
          settings: PSGallery
          output: analysis.sarif
      - name: ⚗️ Test module
        if: hashFiles('/test/*.Tests.ps1','/*.Tests.ps1')
        run: Invoke-Pester -Configuration @{TestResult=@{Enabled=$true}}
      - name: 📤 Upload test results
        if: hashFiles('/test/*.Tests.ps1','/*.Tests.ps1')
        uses: actions/upload-artifact@v7
        with:
          name: Pester test results for ${{ matrix.os }}
          path: ./testResults.xml
